version: '3.7'
services:
  db:
    image: postgres:16
    container_name: bookings_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    
  redis:
    image: redis:7
    container_name: bookings_redis

  bookings:
    image: bookings_app_image
    build:
      context: .
    container_name: bookings_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/bookings/docker/app.sh"]
    ports:
      - 7777:8000

  celery:
    image: bookings_celery_image
    build:
      context: .
    container_name: bookings_celery
    command: ["/bookings/docker/celery.sh", "celery"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  flower:
    image: bookings_flower_image
    build:
      context: .
    container_name: bookings_flower
    command: ["/bookings/docker/celery.sh", "flower"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    ports:
      - 5555:5555